# Generated by Django 4.1.3 on 2023-05-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
