# Generated by Django 4.1.3 on 2023-05-15 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_delete_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', through='news.SubscribersCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
